//Url
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

//Browser
browser = chrome

//Credentials Information
username = Admin
password = admin123

// Implicit Wait in Seconds
implicitwait = 10